import { NgModule } from '@angular/core';
import {
  IconTrash2,
  IconUser,
  IconGithub,
  IconPlus,
  IconMail,
  IconMap,
  IconDollarSign,
  IconCalendar,
  IconSmartphone,
  IconLinkedin,
  IconImage,
  IconBell,
  IconMenu,
  IconBellOff,
  IconXSquare,
  IconPhone,
  IconHelpCircle,
  IconSearch,
  IconX,
  IconChevronDown,
  IconShoppingCart,
  IconMinus,
  IconArrowLeft,
  IconCheck,
  IconCreditCard,
  IconSlash,
  IconLoader,
  IconInfo,
  IconLock,
  IconGlobe,
  IconEdit,
  IconAlertCircle,
  IconHeart,
  IconTrendingDown,
  IconPlay,
  IconUsers,
  IconFacebook,
  IconStar,
  IconShare,
  IconHome
} from 'angular-feather';
import { LoadingAnimationComponent } from './loading/loading.component';

const icons = [
  IconUser,
  IconTrash2,
  IconGithub,
  IconPlus,
  IconMail,
  IconMap,
  IconDollarSign,
  IconCalendar,
  IconSmartphone,
  IconLinkedin,
  IconImage,
  IconBell,
  IconMenu,
  IconBellOff,
  IconXSquare,
  IconPhone,
  IconHelpCircle,
  IconSearch,
  IconX,
  IconChevronDown,
  IconShoppingCart,
  IconMinus,
  IconArrowLeft,
  IconCheck,
  IconCreditCard,
  IconSlash,
  IconLoader,
  IconInfo,
  IconLock,
  IconGlobe,
  IconEdit,
  IconAlertCircle,
  IconHeart,
  IconTrendingDown,
  IconPlay,
  IconUsers,
  IconFacebook,
  IconStar,
  IconShare,
  IconHome,
  LoadingAnimationComponent
];

@NgModule({
  exports: icons,
  declarations: [ LoadingAnimationComponent ]
})
export class IconsModule { }
