import { NgModule } from '@angular/core';
import {
  IconTrash2,
  IconUser,
  IconGithub,
  IconPlus,
  IconMail,
  IconMap,
  IconDollarSign,
  IconCalendar,
  IconSmartphone,
  IconLinkedin,
  IconImage,
  IconBell,
  IconMenu,
  IconBellOff,
  IconXSquare,
  IconPhone,
  IconHelpCircle,
  IconSearch,
  IconX,
  IconChevronDown,
  IconShoppingCart,
  IconMinus,
  IconArrowLeft,
  IconCheck,
  IconCreditCard,
  IconSlash,
  IconLoader,
  IconInfo,
  IconLock,
  IconGlobe,
  IconEdit,
  IconAlertCircle,
  IconHeart,
  IconPlay,
  IconUsers,
  IconFacebook,
  IconStar,
  IconHome,
  IconChevronLeft,
  IconChevronRight,
  IconPlusCircle,
  IconChevronUp,
  IconTwitter,
  IconShare2,
  IconLink,
  IconPercent
} from 'angular-feather';
import { LoadingAnimationComponent } from './loading/loading.component';
import { IWhatsappComponent } from './i-whatsapp/i-whatsapp.component';

const icons = [
  IconUser,
  IconTrash2,
  IconGithub,
  IconTwitter,
  IconPlus,
  IconMail,
  IconMap,
  IconDollarSign,
  IconCalendar,
  IconSmartphone,
  IconLinkedin,
  IconImage,
  IconBell,
  IconMenu,
  IconBellOff,
  IconXSquare,
  IconPhone,
  IconHelpCircle,
  IconSearch,
  IconX,
  IconChevronUp,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconShoppingCart,
  IconMinus,
  IconArrowLeft,
  IconCheck,
  IconCreditCard,
  IconSlash,
  IconLoader,
  IconInfo,
  IconLock,
  IconGlobe,
  IconEdit,
  IconAlertCircle,
  IconHeart,
  IconPercent,
  IconPlay,
  IconUsers,
  IconFacebook,
  IconStar,
  IconShare2,
  IconHome,
  IconGithub,
  IconLinkedin,
  IconPlusCircle,
  LoadingAnimationComponent,
  IWhatsappComponent,
  IconLink
];

@NgModule({
  exports: icons,
  declarations: [ LoadingAnimationComponent, IWhatsappComponent ]
})
export class IconsModule { }
